#pragma once

#include <fontawesome/IconsFontAwesome5.h>

#define EDITOR_ICON_MESH		ICON_FA_CUBE
#define EDITOR_ICON_IMAGE		ICON_FA_FILE_IMAGE
#define EDITOR_ICON_IMAGE_HDR	ICON_FA_CLOUD_SUN
#define EDITOR_ICON_FONT		ICON_FA_FONT
#define EDITOR_ICON_AUDIO		ICON_FA_VOLUME_UP

